FROM kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition

RUN apk update && apk add curl openssh python

CMD sh app/heroku-exec.sh && kong migrations bootstrap && kong start
