version: "2"
services:
  kong-database:
    image: postgres:latest
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_URL: $DATABASE_URL

  kong:
    image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition
    restart: always
    links:
      - kong-database:kong-database
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 7946:7946
      - 7946:7946/udp
    environment:
      - KONG_DATABASE=de6k8hdotvkfrg
      - KONG_PG_HOST=kong-database
