version: "3"
services:
 postgres:
  image: postgres
  restart: always
  container_name: postgres
  volumes:
   - ./docker-pg-mult-db:/docker-entrypoint-initdb.d
  environment:
   - POSTGRES_MULTIPLE_DATABASES=collector
   - POSTGRES_USER=kong
   - POSTGRES_DB=kong
 kong-ent-bootstrap:
  image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:0.36-2-alpine
  container_name: kong-ent-bootstrap
  hostname: kongBootstrap
  depends_on:
   - postgres
  restart: on-failure
  command: "kong migrations bootstrap"
  environment:
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_PASSWORD=XXXXXXX
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
 kong-ent1:
  image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:0.36-2-alpine
  container_name: kong-ent1
  hostname: kongNode1
  depends_on:
   - postgres
   - kong-ent-bootstrap
  restart: always
  ports:
   - 8000:8000
   - 8001:8001
   - 8002:8002
   - 8003:8003
   - 8004:8004
   - 8443:8443
   - 8444:8444
   - 8445:8445
   - 8446:8446
   - 8447:8447
  environment:
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_PASSWORD=XXXXXXX
   - KONG_AUDIT_LOG=on
   - KONG_LOG_LEVEL=debug
   - KONG_PORTAL_GUI_HOST=localhost:8003
   - KONG_PORTAL_GUI_PROTOCOL=http
   - KONG_PORTAL=on
#   - KONG_PORTAL_AUTH=openid-connect
   - KONG_PORTAL_AUTH=basic-auth
   - KONG_ADMIN_GUI_URL=http://localhost:8002
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_CASSANDRA_CONTACT_POINTS=cassandra
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_VITALS=on
  # - KONG_PLUGINS=bundled,mtls-auth
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_ADMIN_GUI_LISTEN=0.0.0.0:8002, 0.0.0.0:8445 ssl
   - KONG_PORTAL_GUI_LISTEN=0.0.0.0:8003, 0.0.0.0:8446 ssl
   - KONG_PORTAL_API_LISTEN=0.0.0.0:8004, 0.0.0.0:8447 ssl
   - KONG_PORTAL_SESSION_CONF={"storage":"kong","cookie_name":"portal_session","secret":"super-secret","cookie_secure":false}  
   - KONG_PORTAL_EMAILS_FROM=portal@xxxx.eu
   - KONG_PORTAL_EMAILS_REPLY_TO=portal@xxxx.eu
   - KONG_SMTP_MOCK=off
   - KONG_SMTP_HOST=mail.xxxx.de
   - KONG_SMTP_PORT=587
   - KONG_SMTP_AUTH_TYPE=plain
   - KONG_SMTP_STARTTLS=on
   - KONG_SMTP_USERNAME=xxx@xxxx.eu
   - KONG_SMTP_PASSWORD='XXXXXXX'
   - KONG_SMTP_ADMIN_EMAILS=xx@xxx.eu
   - KONG_VITALS_STRATEGY=database # or 'influxdb' or 'prometheus' or 'database'
 kong-ent2:
  image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:0.36-2-alpine
  container_name: kong-ent2
  hostname: kongNode2
  depends_on:
   - kong-ent1
   - postgres
  restart: always
  ports:
   - 8010:8000
   - 8012:8002
   - 8013:8003
   - 8014:8004
   - 8453:8443
   - 8455:8445
   - 8456:8446
   - 8457:8447
  environment:
   - KONG_PORTAL=off
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_VITALS=on
   - KONG_ANONYMOUS_REPORTS=off
  # - KONG_PLUGINS=bundled,mtls-auth
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
   - KONG_CUSTOM_PLUGINS=galileo
 kong-ent3:
  image: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition:0.36-2-alpine
  container_name: kong-ent3
  hostname: kongNode3
  depends_on:
   - kong-ent1
   - postgres
  restart: always
  ports:
   - 8020:8000
   - 8022:8002
   - 8023:8003
   - 8024:8004
   - 8463:8443
   - 8465:8445
   - 8466:8446
   - 8467:8447
  command: "kong start"
  environment:
   - KONG_PORTAL=off
   - KONG_ANONYMOUS_REPORTS=off
   - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
   - KONG_DATABASE=postgres
   - KONG_PG_HOST=postgres
   - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
   - KONG_VITALS=on
  # - KONG_PLUGINS=bundled,mtls-auth
   - KONG_PROXY_ACCESS_LOG=/dev/stdout
   - KONG_ADMIN_ACCESS_LOG=/dev/stdout
   - KONG_PROXY_ERROR_LOG=/dev/stderr
   - KONG_ADMIN_ERROR_LOG=/dev/stderr
